# TODO: #: DB에 임시 데이터를 넣기 위한 설정, 필요없어지면 위 주석부분 사용
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql: # 추가
    init: # 추가
      mode: always # 추가
  jpa:
    defer-datasource-initialization: true # 추가
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true